server:
  port: 8080

spring:
  application:
    name: re-online-judge
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/re-oj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    #    url: jdbc:mysql://10.126.126.1:3306/re-oj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jzh030528
  mail:
    host: smtp.qq.com
    port: 587
    username: 1046220903@qq.com
    password: mtcnsxneerxsbbhh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: never
      schema-locations: classpath:re-oj.sql
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.oj.onlinejudge.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jwt:
  header: Authorization
  prefix: Bearer
  secret: 80ry9ew97pgt2973ftg907tgyropwheskmgpaiojrgr90pu809we8yg0whg98ghweagarg4323t2
  expire-minutes: 120
  whitelist:
    - /api/auth/login
    - /api/auth/register
    - /api/auth/register/resendCode
    - /api/auth/verifyEmail
    - /api/auth/password/forgot/sendCode
    - /api/auth/password/forgot/verify

security:
  password:
    salt: change-this-salt

app:
  mail:
    enabled: true
  auth:
    require-email-verify: true
    verify.store: redis
    verify-redis-prefix: "verify:reg:"
  judge:
    async: true
    poll-delay-ms: 1000
    poll-batch-size: 200
  logging:
    login:
      async: true
  storage:
    avatar-dir: ./uploads/avatars
    avatar-url-prefix: /files/avatars

judge0:
  #  base-url: http://139.59.227.54:2358
  base-url: http://localhost:2358
  #  base-url: http://10.126.126.1:2358
  timeout-ms: 15000
  wait: false
  languages:
    11: Bosque (latest)
    3: C3 (latest)
    1: C (Clang 10.0.1)
    2: C++ (Clang 10.0.1)
    13: C (Clang 9.0.1)
    14: C++ (Clang 9.0.1)
    22: C# (Mono 6.12.0.122)
    21: C# (.NET Core SDK 3.1.406)
    15: C++ Test (Clang 10.0.1, Google Test 1.8.1)
    12: C++ Test (GCC 8.4.0, Google Test 1.8.1)
    23: C# Test (.NET Core SDK 3.1.406, NUnit 3.12.0)
    24: F# (.NET Core SDK 3.1.406)
    4: Java (OpenJDK 14.0.1)
    5: Java Test (OpenJDK 14.0.1, JUnit Platform Console Standalone 1.6.2)
    6: MPI (OpenRTE 3.1.3) with C (GCC 8.4.0)
    7: MPI (OpenRTE 3.1.3) with C++ (GCC 8.4.0)
    8: MPI (OpenRTE 3.1.3) with Python (3.7.7)
    89: Multi-file program
    9: Nim (stable)
    10: Python for ML (3.7.7)
    20: Visual Basic.Net (vbnc 0.0.0.5943)
